### ISSUE TITLE
Lets Encrypt certificate not renewed (mobile apps won't download)

### ISSUE THREAD

**Issue by joshmorel** [language-transfer/lt-server#6]
The mobile app won't download new episodes.

It seems this is the issue. The prod server is not renewing the certificate despite the crontab entry.

certbot I think does auto-renew by default now so I don't think should need the cron entry anyways. At least I got it working (initialized via command line instead of a script, and also for Apache). See more: https://techmonger.github.io/49/certbot-auto-renew/

![image](https://user-images.githubusercontent.com/10546720/96452266-cb8b8200-11e6-11eb-8a98-a386388825e1.png)

**Comment by SyntaxBlitz** [comment]
thanks for bringing this up, working on this now

**Comment by SyntaxBlitz** [comment]
oof I'm a dummy, certs were renewing but nginx wasn't restarting

**Comment by SyntaxBlitz** [comment]
@joshmorel Thanks again for bringing this to my attention! It's clear that I need to have alerts set up for things like this. It looks like the issue was live for about 18 hours, but it was only waking up to an email about your Github issue that actually alerted me about it.

**Comment by joshmorel** [comment]
@SyntaxBlitz no problem. Confirmed also downloads are working again from the app.
